//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 12:38:15 PM IST 
//


package com.cg.openbanking.payment.domesticPaymentAPI.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cg.openbanking.payment.domesticPaymentAPI.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cg.openbanking.payment.domesticPaymentAPI.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPartyRequest }
     * 
     */
    public GetPartyRequest createGetPartyRequest() {
        return new GetPartyRequest();
    }

    /**
     * Create an instance of {@link GetPartyResponse }
     * 
     */
    public GetPartyResponse createGetPartyResponse() {
        return new GetPartyResponse();
    }

    /**
     * Create an instance of {@link Partyinfo }
     * 
     */
    public Partyinfo createPartyinfo() {
        return new Partyinfo();
    }

    /**
     * Create an instance of {@link Addressinfo }
     * 
     */
    public Addressinfo createAddressinfo() {
        return new Addressinfo();
    }

}
